### ISSUE TITLE
Example of Copier integration on README

### ISSUE THREAD

**Issue by yajo** [copier-org/jinja2-jsonschema#1]
### Actual Situation

Since https://github.com/copier-org/copier/pull/1146, this extension is recommended within Copier itself.

The README explains general usage for any jinja environment. Although it's well explained, it requires some technical knowledge on the inner workings of Copier to know for example where the schemas will be looked for in a template.

### Desired Situation

Since this extension exists inside copier-org, I think it's perfectly fine to give a some example of a copier template using it.

### Proposed solution

Improve docs?

**Comment by sisp** [comment]
Good idea! I'll add a section on Copier integration in the README.
